// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQOz20HZylFd_8IfqWq359G8pZVYMloU',
    appId: '1:680010314774:web:0c9b0ab6e21e2027267137',
    messagingSenderId: '680010314774',
    projectId: 'my-gate-a04b6',
    authDomain: 'my-gate-a04b6.firebaseapp.com',
    storageBucket: 'my-gate-a04b6.firebasestorage.app',
    measurementId: 'G-P920KZB1MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYBcqOA4PKKazjNoqIh9r7hDGh7B3IVI',
    appId: '1:680010314774:android:4475108cb8affe36267137',
    messagingSenderId: '680010314774',
    projectId: 'my-gate-a04b6',
    storageBucket: 'my-gate-a04b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUl-zmTgte0otyWZN1AJX5Y5Evc9wseiM',
    appId: '1:680010314774:ios:67c855734c4f033d267137',
    messagingSenderId: '680010314774',
    projectId: 'my-gate-a04b6',
    storageBucket: 'my-gate-a04b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUl-zmTgte0otyWZN1AJX5Y5Evc9wseiM',
    appId: '1:680010314774:ios:67c855734c4f033d267137',
    messagingSenderId: '680010314774',
    projectId: 'my-gate-a04b6',
    storageBucket: 'my-gate-a04b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAQOz20HZylFd_8IfqWq359G8pZVYMloU',
    appId: '1:680010314774:web:ebc277043d4cb852267137',
    messagingSenderId: '680010314774',
    projectId: 'my-gate-a04b6',
    authDomain: 'my-gate-a04b6.firebaseapp.com',
    storageBucket: 'my-gate-a04b6.firebasestorage.app',
    measurementId: 'G-G6ZDQE5Z7N',
  );
}
