// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSMiQCLmiqwsFPSjFAE4dPOB0jrqcJYo',
    appId: '1:812984256624:web:434bf28b6aeeb55ddd0cb5',
    messagingSenderId: '812984256624',
    projectId: 'vmsweb-ba516',
    authDomain: 'vmsweb-ba516.firebaseapp.com',
    storageBucket: 'vmsweb-ba516.firebasestorage.app',
    measurementId: 'G-93EGNPW0X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMGZONYqaRKPxpzBqctlaDUTa-5bGM7I0',
    appId: '1:812984256624:android:e03e5e035042694cdd0cb5',
    messagingSenderId: '812984256624',
    projectId: 'vmsweb-ba516',
    storageBucket: 'vmsweb-ba516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXOiibYsEoUXnOQKHHMIxiyiyJaBT4nps',
    appId: '1:812984256624:ios:7df729627ad2b3bbdd0cb5',
    messagingSenderId: '812984256624',
    projectId: 'vmsweb-ba516',
    storageBucket: 'vmsweb-ba516.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXOiibYsEoUXnOQKHHMIxiyiyJaBT4nps',
    appId: '1:812984256624:ios:7df729627ad2b3bbdd0cb5',
    messagingSenderId: '812984256624',
    projectId: 'vmsweb-ba516',
    storageBucket: 'vmsweb-ba516.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSMiQCLmiqwsFPSjFAE4dPOB0jrqcJYo',
    appId: '1:812984256624:web:c9f3ccca6defe2dedd0cb5',
    messagingSenderId: '812984256624',
    projectId: 'vmsweb-ba516',
    authDomain: 'vmsweb-ba516.firebaseapp.com',
    storageBucket: 'vmsweb-ba516.firebasestorage.app',
    measurementId: 'G-JVW51TCRCQ',
  );
}
