// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:firebase_auth/firebase_auth.dart' as fbAuth;
// import 'package:flutter_application_1/src/ui/guard/home.dart' show GuardHomePage;
// import 'package:provider/provider.dart';

// // Firebase setup
// import 'firebase_options.dart';
// import 'notification_service.dart';
// import 'src/fcm_background_handler.dart' show firebaseMessagingBackgroundHandler;

// // Dashboards
// import 'src/ui/owner/owner_dashboard.dart';
// import 'src/ui/guard/GuardDashboard.dart';
// import 'src/ui/shared/role_selection.dart';

// // Providers
// import 'src/providers/auth_provider.dart';

// // Models
// import 'src/models/user_model.dart';

// Future<void> main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   // ---------- Guarded Firebase init ----------
//   // Some plugins or other code paths may initialize Firebase automatically,
//   // so protect against duplicate initialization which throws [core/duplicate-app].
//   try {
//     // Debug: list existing apps (in development this can help)
//     try {
//       debugPrint('Before init: Firebase.apps = ${Firebase.apps.map((a) => a.name).toList()}');
//     } catch (_) {}

//     if (Firebase.apps.isEmpty) {
//       // Use platform-specific options generated by flutterfire CLI if available.
//       await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
//       debugPrint('Firebase.initializeApp() completed.');
//     } else {
//       debugPrint('Firebase already initialized — skipping initializeApp().');
//     }
//   } on FirebaseException catch (e) {
//     // If an initialize race still results in duplicate-app, ignore it and continue.
//     if (e.code == 'duplicate-app') {
//       debugPrint('Caught duplicate-app FirebaseException — continuing.');
//     } else {
//       // If some other Firebase exception occurred, rethrow so you don't hide real problems.
//       rethrow;
//     }
//   } catch (e) {
//     // Any other unexpected error — log and rethrow to avoid masking issues.
//     debugPrint('Unexpected error during Firebase initialization: $e');
//     rethrow;
//   }

//   // Background FCM handler MUST be a top-level function (already done in your file).
//   FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

//   // Initialize local notification service (ensure it does NOT call Firebase.initializeApp again)
//   await NotificationService().init();

//   runApp(const MyGateApp());
// }

// class MyGateApp extends StatefulWidget {
//   const MyGateApp({super.key});

//   @override
//   State<MyGateApp> createState() => _MyGateAppState();
// }

// class _MyGateAppState extends State<MyGateApp> with WidgetsBindingObserver {
//   @override
//   void initState() {
//     super.initState();
//     WidgetsBinding.instance.addObserver(this);
//     _setupFCM();
//   }

//   @override
//   void dispose() {
//     WidgetsBinding.instance.removeObserver(this);
//     super.dispose();
//   }

//   // Optional: observe lifecycle changes for debugging
//   @override
//   void didChangeAppLifecycleState(AppLifecycleState state) {
//     debugPrint('AppLifecycleState changed: $state');
//   }

//   Future<void> _setupFCM() async {
//     final messaging = FirebaseMessaging.instance;

//     // Request notification permissions
//     NotificationSettings settings = await messaging.requestPermission(
//       alert: true,
//       badge: true,
//       sound: true,
//     );
//     debugPrint("Notification permission: ${settings.authorizationStatus}");

//     // Get current logged in user
//     fbAuth.User? firebaseUser = fbAuth.FirebaseAuth.instance.currentUser;
//     String? userId = firebaseUser?.uid;

//     // Fetch FCM token
//     String? token;
//     try {
//       token = await messaging.getToken();
//     } catch (e) {
//       debugPrint('Error getting FCM token: $e');
//       token = null;
//     }

//     // Save token to Firestore
//     if (token != null && userId != null) {
//       try {
//         await FirebaseFirestore.instance.collection("users").doc(userId).update(
//           {"fcmToken": token},
//         );

//         debugPrint("FCM Token saved: $token");
//       } catch (e) {
//         debugPrint("Error saving token: $e");
//       }
//     }

//     // Listen for token refresh
//     FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
//       if (userId != null) {
//         try {
//           await FirebaseFirestore.instance.collection("users").doc(userId).update(
//             {"fcmToken": newToken},
//           );
//           debugPrint("FCM Token refreshed: $newToken");
//         } catch (e) {
//           debugPrint("Error updating refreshed token: $e");
//         }
//       }
//     });

//     // Foreground notifications
//     FirebaseMessaging.onMessage.listen((RemoteMessage message) {
//       final notification = message.notification;
//       final data = message.data;

//       NotificationService().showNotification(
//         id: DateTime.now().millisecondsSinceEpoch ~/ 1000,
//         title: notification?.title ?? data['title'] ?? "New Alert",
//         body: notification?.body ?? data['body'] ?? "",
//         payload: data,
//       );
//     });

//     // When user taps notification (background / terminated)
//     FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) async {
//       WidgetsBinding.instance.addPostFrameCallback((_) async {
//         if (userId == null) return;

//         try {
//           final userDoc = await FirebaseFirestore.instance
//               .collection("users")
//               .doc(userId)
//               .get();

//           if (!userDoc.exists) return;

//           final data = userDoc.data()!;
//           final role = data["role"];

//           // Owner
//           if (role == "owner") {
//             final ownerModel = UserModel.fromMap(data, userId);
//             Navigator.push(
//               context,
//               MaterialPageRoute(
//                 builder: (_) => OwnerDashboard(loggedInOwner: ownerModel),
//               ),
//             );
//           }
//           // Guard
//           else if (role == "guard") {
//             Navigator.push(
//               context,
//               MaterialPageRoute(builder: (_) => GuardHomePage()),
//             );
//           }
//           // Role selection (fallback)
//           else {
//             Navigator.push(
//               context,
//               MaterialPageRoute(builder: (_) => const RoleSelectionPage()),
//             );
//           }
//         } catch (e) {
//           debugPrint("Navigation error on notification tap: $e");
//         }
//       });
//     });
//   }

//   @override
//   Widget build(BuildContext context) {
//     return MultiProvider(
//       providers: [ChangeNotifierProvider(create: (_) => AuthProvider())],
//       child: MaterialApp(
//         debugShowCheckedModeBanner: false,
//         title: "MyGate App",
//         home: const RoleSelectionPage(),
//       ),
//     );
//   }
// }
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart' as fbAuth;
import 'package:flutter_application_1/src/ui/guard/home.dart'
    show GuardHomePage;
import 'package:provider/provider.dart';

// Firebase setup
import 'firebase_options.dart';
import 'notification_service.dart';
import 'src/fcm_background_handler.dart'
    show firebaseMessagingBackgroundHandler;

// Dashboards
import 'src/ui/owner/owner_dashboard.dart';
import 'src/ui/shared/role_selection.dart';

// Providers
import 'src/providers/auth_provider.dart';

// Models
import 'src/models/user_model.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Safe Firebase initialization
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('✅ Firebase initialized');
    }
  } catch (e) {
    debugPrint('Firebase init error: $e');
  }

  // ✅ ADD THIS: Firestore offline persistence (FAST writes)
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
  );

  // ✅ Background FCM handler
  FirebaseMessaging.onBackgroundMessage(
    firebaseMessagingBackgroundHandler,
  );

  // ✅ Local notification init
  await NotificationService().init();

  runApp(const MyGateApp());
}

class MyGateApp extends StatefulWidget {
  const MyGateApp({super.key});

  @override
  State<MyGateApp> createState() => _MyGateAppState();
}

class _MyGateAppState extends State<MyGateApp>
    with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _setupFCM();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  Future<void> _setupFCM() async {
    final messaging = FirebaseMessaging.instance;

    // 🔔 Request permission
    final settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
    debugPrint('🔔 Permission: ${settings.authorizationStatus}');

    // 📱 Get FCM token
    final token = await messaging.getToken();
    debugPrint('🔥 FCM TOKEN: $token');

    // 👤 Current user
    final fbAuth.User? user =
        fbAuth.FirebaseAuth.instance.currentUser;

    // 💾 Save token
    if (token != null && user != null) {
      await FirebaseFirestore.instance
          .collection("users")
          .doc(user.uid)
          .set(
        {"fcmToken": token},
        SetOptions(merge: true),
      );
    }

    // 🔁 Token refresh
    FirebaseMessaging.instance.onTokenRefresh.listen(
      (newToken) async {
        final fbAuth.User? u =
            fbAuth.FirebaseAuth.instance.currentUser;
        if (u != null) {
          await FirebaseFirestore.instance
              .collection("users")
              .doc(u.uid)
              .set(
            {"fcmToken": newToken},
            SetOptions(merge: true),
          );
          debugPrint('🔄 FCM token refreshed');
        }
      },
    );

    // 📩 Foreground notifications
    FirebaseMessaging.onMessage.listen(
      (RemoteMessage message) {
        final n = message.notification;
        final d = message.data;

        NotificationService().showNotification(
          id: DateTime.now().millisecondsSinceEpoch ~/ 1000,
          title: n?.title ?? d['title'] ?? "New Alert",
          body: n?.body ?? d['body'] ?? "",
          payload: d,
        );
      },
    );

    // 📲 App opened from background
    FirebaseMessaging.onMessageOpenedApp.listen(
      (RemoteMessage message) {
        _handleNotificationNavigation(message.data);
      },
    );

    // 🧊 App opened from terminated
    final initialMessage =
        await FirebaseMessaging.instance.getInitialMessage();
    if (initialMessage != null) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        _handleNotificationNavigation(initialMessage.data);
      });
    }
  }

  Future<void> _handleNotificationNavigation(
      Map<String, dynamic> data) async {
    if (!mounted) return;

    final fbAuth.User? user =
        fbAuth.FirebaseAuth.instance.currentUser;
    if (user == null) return;

    final snap = await FirebaseFirestore.instance
        .collection("users")
        .doc(user.uid)
        .get();

    if (!snap.exists) return;

    final role = snap.data()?['role'];
    final type = data['type'];

    if (role == 'owner') {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => OwnerDashboard(
            loggedInOwner: UserModel.fromMap(
              snap.data()!,
              user.uid,
            ),
          ),
        ),
      );

      if (type == 'visitor' || type == 'vehicle') {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          DefaultTabController.of(context)?.animateTo(0);
        });
      }
    } else if (role == 'guard') {
      Navigator.push(
        context,
        MaterialPageRoute(builder: (_) => GuardHomePage()),
      );
    } else {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => const RoleSelectionPage(),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
      ],
      child: const MaterialApp(
        debugShowCheckedModeBanner: false,
        title: "MyGate App",
        home: RoleSelectionPage(),
      ),
    );
  }
}
